language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install gfortran libblas-dev liblapack-dev libilmbase-dev
  - sudo pip install cpp-coveralls --use-mirrors

script:
  - make double float lapack fortran half
  - make check
  - make -C examples checklapack LDADD_L='-llapack -lblas'
  - make veryclean
  - make -k -C examples ftest test ctest testdrv ctestdrv CFLAGS='-g -fprofile-arcs -ftest-coverage -Wall -Wextra -Werror' FFLAGS='-g -fprofile-arcs -ftest-coverage'
#  - make double fortran CFLAGS='-g -fprofile-arcs -ftest-coverage -Wall -Wextra -Werror' FFLAGS='-g -fprofile-arcs -ftest-coverage'
#  - make -C examples checkdouble CFLAGS='-g -fprofile-arcs -ftest-coverage -Wall -Wextra -Werror' FFLAGS='-g -fprofile-arcs -ftest-coverage'

after_success:
  - coveralls --exclude examples
